
apiVersion: v1
kind: Service
metadata:
  name: {{ include "integration-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5555
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "integration-server.name" . }}
