image:
  repository: softwareag/command-central
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 8091
  nodePort: 30006

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
