# /*
#  * Copyright (c) 2021 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */
{{- if .Values.elasticsearch.deploy }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "common.names.fullname" . }}
spec:
  version: {{ .Values.elasticsearch.version }}
  {{- if .Values.elasticsearch.image }}
  image: {{ .Values.elasticsearch.image }}
  {{- end }}
  http:
    tls:
    {{- if .Values.elasticsearch.tlsEnabled }}
      certificate: 
        secretName: {{ tpl .Values.elasticsearch.certificateSecretName . }} 
    {{- end }}
      selfSignedCertificate:
        disabled: true
  auth:
    fileRealm:
    - secretName: {{ include "developerportal.elasticsecret" . }}-es
  nodeSets:
  {{- if .Values.nodeSets }}
    {{- toYaml .Values.elasticsearch.nodeSets | nindent 6 }}
  {{ else }}
    # use default node set
    - name: default
      count: {{ .Values.elasticsearch.defaultNodeSet.count }}
      config:
        {{- if not .Values.elasticsearch.defaultNodeSet.memoryMapping  }}
        node.store.allow_mmap: false
        {{- end }}
        xpack.security.authc:
          anonymous:
            username: sag-user
            roles: superuser
            authz_exception: false
      podTemplate:
        spec:
          initContainers:
          {{- if and .Values.elasticsearch.defaultNodeSet.setMaxMapCount .Values.elasticsearch.defaultNodeSet.memoryMapping }}
          - name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          {{- end }}
          {{- if .Values.elasticsearch.defaultNodeSet.installPlugins }}
          - name: install-plugins
            command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install --batch {{ range .Values.elasticsearch.defaultNodeSet.installPlugins }} {{ . }} {{- end }}
          {{- end }}
  {{- end }}
{{- end }}