image:
  repository: softwareag/optimize-server
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 8080
  nodePort: 30004

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
