apiVersion: v1
kind: Service
metadata:
  name: {{ include "command-central.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8091
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "command-central.name" . }}
