apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "optimize-server.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: optimize-server.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "optimize-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
