image:
  repository: softwareag/integration-server
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 5555
  nodePort: 30001

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
